# Generated by Django 4.0.3 on 2022-04-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogr2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('aciklama', models.TextField(max_length=250)),
                ('resim', models.FileField(blank=True, null=True, upload_to='kisiresmi/', verbose_name='kisi Resmi Ekleyin')),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anasayfa.ogr')),
            ],
        ),
    ]
